# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='current_alt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='current_lang',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='current_long',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='current_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
